wandb_version: 1

_wandb:
  desc: null
  value:
    cli_version: 0.12.10
    code_path: code/utils/reject_utils.py
    is_jupyter_run: true
    is_kaggle_kernel: false
    python_version: 3.8.10
    start_time: 1645254936
    t:
      3:
      - 13
      4: 3.8.10
      5: 0.12.10
      8:
      - 1
      - 5
    visualize:
      Rejection Application Year Wise:
        panel_config:
          fieldSettings:
            stroke: null
            x: year
            y: count
          panelDefId: wandb/line/v0
          stringSettings:
            title: Rejection Application Year Wise
          transform:
            name: tableWithLeafColNames
          userQuery:
            queryFields:
            - args:
              - name: runSets
                value: ${runSets}
              fields:
              - fields: []
                name: id
              - fields: []
                name: name
              - fields: []
                name: _defaultColorIndex
              - args:
                - name: tableKey
                  value: Rejection Application Year Wise_table
                fields: []
                name: summaryTable
              name: runSets
        panel_type: Vega2
